Vagrant.configure("2") do |config|
  # Configuración general de la VM
  config.vm.box = "ubuntu/bionic64"

  # Aumentar el tiempo de espera de arranque
  config.vm.boot_timeout = 900

  # Configuración del nodo maestro
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.5"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    master.vm.provision "shell", inline: <<-SHELL
      echo "Updating and installing dependencies..."
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y curl build-essential dkms linux-headers-$(uname -r) --fix-missing

      echo "Downloading and installing K3s..."
      curl -sfL https://get.k3s.io | sh -

      echo "Displaying K3s token..."
      cat /var/lib/rancher/k3s/server/node-token
    SHELL
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.6"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    worker.vm.provision "shell", inline: <<-SHELL
      # Actualizar e instalar dependencias
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y curl build-essential dkms linux-headers-$(uname -r) --fix-missing

      # Unirse al clúster K3s
      K3S_URL=https://192.168.56.5:6443
      K3S_TOKEN=$(curl -sfL $K3S_URL | grep 'node-token' | awk '{print $2}')
      curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -
    SHELL
  end
end
