# Chart.yaml
apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.0"

# values.yaml
replicaCount: 2

image:
  repository: myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {? {.Chart.Name: ''} : ''}
spec:
  replicas: {? {.Values.replicaCount: ''} : ''}
  selector:
    matchLabels:
      app: {? {.Chart.Name: ''} : ''}
  template:
    metadata:
      labels:
        app: {? {.Chart.Name: ''} : ''}
    spec:
      containers:
      - name: {? {.Chart.Name: ''} : ''}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
