apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-access
  namespace: tech-prod
spec:
  podSelector:
    matchLabels:
      app: python-microservice
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
